### ISSUE TITLE
[BUG] [Formatter] extend_exclude does not work anymore 1.36.2

### ISSUE THREAD

**Issue by Zerotask** [djlint/djLint#1047]
- [ ] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [ ] I've searched the [issues](https://github.com/djlint/djLint/issues)
- [ ] I've read the [docs](https://djlint.com)

## System Info

- OS: macOS 15.1.1
- Python Version: 3.12.7
- djLint Version: 1.36.2
- template language: django

## Issue

After the update to 1.36.2 we noticed that a lot of files were formatted which were excluded in previous versions.
Is this a bug or an expected breaking change?

## How To Reproduce

```toml
[tool.djlint] # 
extend_exclude = "venv/,staticfiles/,.vscode/,.github/,node_modules/,templates/layout/base_email.html,.idea/,.tests/,.cache/,emails/"
```

Folder: `apps/account/templates/user/emails/test.html`

All html files inside this emails folder should be excluded. This was the behavior with the previous 1.35.x version.
